import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

// eslint-config-next ships flat config from v16, so this uses it directly
// rather than through the eslintrc compatibility shim.
const config = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      ".next/**",
      "out/**",
      // Generated by `npm run build-report`, and not source.
      "src/generated/**",
      "source-data/**",
    ],
  },
];

export default config;
